customers:
  exampleCustomer:
    code: EC
    fullName: Example Customer
    invoicePath: ./invoices/ExampleCustomer/
fullName: Callum Walley
ledgerPath: example/ledger.beancount
timesheetPath: example/timesheet.beancount
hourlyRate: 55
