customers:
  exampleCustomer:
    code: EC1
    fullName: Example Customer
    archivePath: example/invoicedTimesheets/{slug}/{min_date}_{max_date}.beancount
    invoicePath: 
      - example/invoices/{slug}/{code}{count}.pdf
      - example/invoices/{slug}/{code}{count}.html
fullName: Callum Walley
ledgerPath: example/ledger.beancount
timesheetPath: example/timesheet.beancount
hourlyRate: 55
